### ISSUE TITLE
Results of this repo in CI/CD

### ISSUE THREAD

**Issue by bjarkihall** [waldo1001/waldo.BCPerfTool#2]
Hi,

I saw your great talk at BcTechdays 22 and was curious to see if the app itself was being run via Github Actions.

It would be cool to see the results of the demo benchmarks you made somehow here on Github, if possible. I think I spotted AL-Go being used here but the recent builds were failing and I think it was mainly to build the app, not publishing and running the demos and collecting the results, right?

It would make it possible to see how BC performs once MS release new updates, to spot improvements/regressions for some of the cases you've been testing.

Also if someone in the future is checking out this repo, here is the link to the talk waldo made:
https://www.youtube.com/watch?v=E3ADZsisFbE

**Comment by waldo1001** [comment]
The build is fixed - had to involve Freddy 🙈.

It seems to be a combo of my dependency with a default MS app - which it doesn't "just" grab in AL-Go.. .
